Update up

diff --git a/docker/root/etc/s6-overlay/s6-rc.d/init-env/up b/docker/root/etc/s6-overlay/s6-rc.d/init-env/up
--- a/docker/root/etc/s6-overlay/s6-rc.d/init-env/up
+++ b/docker/root/etc/s6-overlay/s6-rc.d/init-env/up
@@ -1,8 +1,17 @@
 #!/command/with-contenv bash
 # shellcheck shell=bash
+
+# Set MySQL environment variables
 echo "lgclvdnmj1492" > /run/s6/container_environment/MYSQL_ROOT_PASSWORD
 echo "kodi_video131" > /run/s6/container_environment/MYSQL_DATABASE
 echo "kodi" > /run/s6/container_environment/MYSQL_USER
 echo "kodi" > /run/s6/container_environment/MYSQL_PASSWORD
 echo "/jellygrail/data/mysql" > /run/s6/container_environment/DATADIR
-chown -R mysql:mysql /jellygrail/data/mysql
+
+# Ensure the MySQL data directory has the correct permissions
+if [ -d "/jellygrail/data/mysql" ]; then
+  chown -R mysql:mysql /jellygrail/data/mysql
+else
+  echo "Error: /jellygrail/data/mysql directory does not exist."
+  exit 1
+fi
